// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cart.proto

package cart

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Cart service

func NewCartEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Cart service

type CartService interface {
	// 加入购物车，status设置为0 表示等待支付状态
	Add(ctx context.Context, in *AddCartRequest, opts ...client.CallOption) (*AddCartResponse, error)
	// 更新数量
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	// 从购物车中删除某个商品，把这个商品的status设置为2，表示discard
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	FindAll(ctx context.Context, in *FindAllCartRequest, opts ...client.CallOption) (*FindAllCartResponse, error)
	// checkout cart 下单，需要创建一条order表的记录并且插入到order表中
	// 把所有这个user的商品信息搜集起来，并且计算总金额， 在这个过程中需要把每个商品的status标记为1，也就是“被结算”状态
	// 写一条记录，这个记录是要插入到order表中，并且等待支付
	CheckOutCart(ctx context.Context, in *CheckOutCartRequest, opts ...client.CallOption) (*CheckOutCartResponse, error)
}

type cartService struct {
	c    client.Client
	name string
}

func NewCartService(name string, c client.Client) CartService {
	return &cartService{
		c:    c,
		name: name,
	}
}

func (c *cartService) Add(ctx context.Context, in *AddCartRequest, opts ...client.CallOption) (*AddCartResponse, error) {
	req := c.c.NewRequest(c.name, "Cart.Add", in)
	out := new(AddCartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "Cart.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "Cart.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) FindAll(ctx context.Context, in *FindAllCartRequest, opts ...client.CallOption) (*FindAllCartResponse, error) {
	req := c.c.NewRequest(c.name, "Cart.FindAll", in)
	out := new(FindAllCartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) CheckOutCart(ctx context.Context, in *CheckOutCartRequest, opts ...client.CallOption) (*CheckOutCartResponse, error) {
	req := c.c.NewRequest(c.name, "Cart.CheckOutCart", in)
	out := new(CheckOutCartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cart service

type CartHandler interface {
	// 加入购物车，status设置为0 表示等待支付状态
	Add(context.Context, *AddCartRequest, *AddCartResponse) error
	// 更新数量
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	// 从购物车中删除某个商品，把这个商品的status设置为2，表示discard
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	FindAll(context.Context, *FindAllCartRequest, *FindAllCartResponse) error
	// checkout cart 下单，需要创建一条order表的记录并且插入到order表中
	// 把所有这个user的商品信息搜集起来，并且计算总金额， 在这个过程中需要把每个商品的status标记为1，也就是“被结算”状态
	// 写一条记录，这个记录是要插入到order表中，并且等待支付
	CheckOutCart(context.Context, *CheckOutCartRequest, *CheckOutCartResponse) error
}

func RegisterCartHandler(s server.Server, hdlr CartHandler, opts ...server.HandlerOption) error {
	type cart interface {
		Add(ctx context.Context, in *AddCartRequest, out *AddCartResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
		FindAll(ctx context.Context, in *FindAllCartRequest, out *FindAllCartResponse) error
		CheckOutCart(ctx context.Context, in *CheckOutCartRequest, out *CheckOutCartResponse) error
	}
	type Cart struct {
		cart
	}
	h := &cartHandler{hdlr}
	return s.Handle(s.NewHandler(&Cart{h}, opts...))
}

type cartHandler struct {
	CartHandler
}

func (h *cartHandler) Add(ctx context.Context, in *AddCartRequest, out *AddCartResponse) error {
	return h.CartHandler.Add(ctx, in, out)
}

func (h *cartHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.CartHandler.Update(ctx, in, out)
}

func (h *cartHandler) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.CartHandler.Delete(ctx, in, out)
}

func (h *cartHandler) FindAll(ctx context.Context, in *FindAllCartRequest, out *FindAllCartResponse) error {
	return h.CartHandler.FindAll(ctx, in, out)
}

func (h *cartHandler) CheckOutCart(ctx context.Context, in *CheckOutCartRequest, out *CheckOutCartResponse) error {
	return h.CartHandler.CheckOutCart(ctx, in, out)
}
